### ISSUE TITLE
Dice 计算错误？

### ISSUE THREAD

**Issue by LiangDazhu** [Algolzw/SPAC-Deformable-Registration#4]
您好， 我在复现您论文时，发现了个问题， 麻烦您解答下：
在test.py
 `scores = utils.dice(fixed_seg>0, warped_seg>0, [1])`
env.py
`            dices = utils.dice(self.fixed_seg[0, 0]>0,
                utils.numpy_im(self.moved_seg, 1, device=self.device)>0)`
中计算Dice时，都是传入的 fixed_seg[0, 0]>0 , 这样在dice函数中，得到的label将会是True或者False, 当移除False(`labels = np.delete(labels, np.where(labels == 0))`)后， 其实计算的并不是各类别的Dice，而是把所有类别都当作一类别计算的Dice,这样就导致了计算的Dice结果值异常高

**Comment by Algolzw** [comment]
这里是因为我们测SLIVER和LSPIG的时候其本身就只有一个类别（ROI），所以使用labels==1表示ROI，labels==0表示其他区域。如果你要测试其他数据集最好重新写一个test代码。

**Comment by LiangDazhu** [comment]
好的， 谢谢
